import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
"use client";

import { ReactNode } from "react";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { Sidebar } from "@/components/sidebar";
import { LoadingState } from "@/components/ui";

interface LayoutProps {
  children: ReactNode;
}

export default function ProtectedLayout({ children }: LayoutProps) {
  const pathname = usePathname();
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const [userRole, setUserRole] = useState<string>("EMPLOYEE");
  const [userName, setUserName] = useState<string>("User");

  useEffect(() => {
    // Check if user is authenticated
    const checkAuth = async () => {
      try {
        // TODO: Replace with actual auth API call when Person 1 completes auth
        // const res = await fetch("/api/auth/me", {
        //   credentials: "include",
        // });
        // if (!res.ok) {
        //   router.push("/login");
        //   return;
        // }
        // const user = await res.json();
        // setUserRole(user.role);
        // setUserName(`${user.firstName} ${user.lastName}`);

        // Temp: assume user is logged in
        setUserRole("EMPLOYEE");
        setUserName("John Doe");
      } catch (err) {
        console.error("Auth check failed:", err);
        router.push("/login");
      } finally {
        setLoading(false);
      }
    };

    if (pathname !== "/login" && pathname !== "/signup") {
      checkAuth();
    } else {
      setLoading(false);
    }
  }, [pathname, router]);

  if (pathname === "/login" || pathname === "/signup") {
    return children;
  }

  if (loading) {
    return <LoadingState message="Loading..." />;
  }

  return (
    <div className="flex bg-slate-950 min-h-screen">
      <Sidebar userRole={userRole} userName={userName} />
      <main className="flex-1 md:ml-0 p-4 md:p-8 mt-16 md:mt-0">
        {children}
      </main>
    </div>
  );
}